const COMPANIES = {
  PNP: 'PNP',
  PIA: 'PIA',
  PHR: 'PHR',
  PHN: 'PHN',
  PAC: 'PAC',
  NT2: 'NT2',
  IMP: 'IMP',
  HCM: 'HCM',
  FPT: 'FPT',
  DXP: 'DXP',
  DWC: 'DWC',
  DPR: 'DPR',
  DNC: 'DNC',
  DM7: 'DM7',
  CTG: 'CTG',
  CPC: 'CPC',
  CHP: 'CHP',
  VDP: 'VDP',
  THG: 'THG',
  TDW: 'TDW',
  PPP: 'PPP',
  PMP: 'PMP',
  MVC: 'MVC',
  MIG: 'MIG',
  DHG: 'DHG',
  CTB: 'CTB',
  PRE: 'PRE',
  NO1: 'NO1',
  HUB: 'HUB',
  HCC: 'HCC',
  DTP: 'DTP',
  DP1: 'DP1',
  CLL: 'CLL',
  ADC: 'ADC',
  WSB: 'WSB',
  VMS: 'VMS',
  TNG: 'TNG',
  QHD: 'QHD',
  LGC: 'LGC',
  GMX: 'GMX'
};

const CAFEF_API = `https://cafef.vn/du-lieu/Ajax/CongTy/BaoCaoTaiChinh.aspx?sym=`;

export { COMPANIES, CAFEF_API };